dataset:
  edge_encoder: true
  edge_encoder_name: Bond
  format: OGB
  name: ogbg-molhiv
  node_encoder: true
  node_encoder_name: Atom
  task: graph
  task_type: classification
gnn:
  act: swish
  agg: max
  batchnorm: false
  dim_inner: 300
  dropout: 0.3
  layer_type: generalconv
  layers_mp: 3
  layers_post_mp: 2
  layers_pre_mp: 2
  normalize_adj: false
  stage_type: skipsum
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: cross_entropy
  type: gnn
optim:
  base_lr: 0.01
  max_epoch: 100
  optimizer: adam
out_dir: results
train:
  batch_size: 128
  ckpt_period: 100
  eval_period: 1
  sampler: full_batch
