dataset:
  edge_encoder: false
  edge_encoder_name: Bond
  format: OGB
  name: ogbn-arxiv
  node_encoder: false
  node_encoder_name: Atom
  task: node
  task_type: classification
gnn:
  act: relu
  agg: sum
  batchnorm: true
  dim_inner: 128
  dropout: 0.3
  layer_type: ginconv
  layers_mp: 1
  layers_post_mp: 2
  layers_pre_mp: 2
  normalize_adj: false
  stage_type: skipconcat
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: cross_entropy
  type: gnn
optim:
  base_lr: 0.01
  max_epoch: 200
  optimizer: adam
out_dir: results
train:
  batch_size: 128
  ckpt_period: 100
  eval_period: 1
  sampler: full_batch
